export enum TIPOS_ACOES {
  //enums de projetos
  OBTER_PROJETOS = 'OBTER_PROJETOS',
  CADASTRAR_PROJETO = 'CADASTRAR_PROJETO',
  ALTERAR_PROJETO = 'ALTERAR_PROJETO',
  REMOVER_PROJETO = 'REMOVER_PROJETO',

  //enums de tarefas
  OBTER_TAREFAS = 'OBTER_TAREFAS',
  CADASTRAR_TAREFA = 'CADASTRAR_TAREFA',
  REMOVER_TAREFA = 'REMOVER_TAREFA',
  ALTERAR_TAREFA = 'ALTERAR_TAREFA',
}
