export enum TIPOS_MUTACOES {
  //enums de projetos
  DEFINIR_PROJETOS = 'DEFINIR_PROJETOS',
  ADICIONAR_PROJETO = 'ADICIONAR_PROJETO',
  ALTERAR_PROJETO = 'ALTERAR_PROJETO',
  EXCLUIR_PROJETO = 'EXCLUIR_PROJETO',

  //enums de tarefas
  DEFINIR_TAREFAS = 'DEFINIR_TAREFAS',
  ADICIONAR_TAREFA = 'ADICIONAR_TAREFA',
  REMOVER_TAREFA = 'REMOVER_TAREFA',
  ALTERAR_TAREFA = 'ALTERAR_TAREFA',

  //enums de notificações
  NOTIFICAR = 'NOTIFICAR',
}
