export enum TIPOS_MUTACOES {
  ADICIONAR_PROJETO = 'ADICIONAR_PROJETO',
  ALTERAR_PROJETO = 'ALTERAR_PROJETO',
  EXCLUIR_PROJETO = 'EXCLUIR_PROJETO',
  ADICIONAR_TAREFA = 'ADICIONAR_TAREFA',
  REMOVER_TAREFA = 'REMOVER_TAREFA',
  NOTIFICAR = 'NOTIFICAR',
}
